databases:
  - name: everchords
    databaseName: everchords_production
    user: everchords
    region: frankfurt

services:
  - type: web
    name: everchords
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: everchords
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
