default: &default
  consumer_key: <%= ENV['EN_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['EN_CONSUMER_SECRET'] %>
  sandbox: true
  url: https://sandbox.evernote.com

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  sandbox: false
  url: https://www.evernote.com
