default: &default
  consumer_key: <%= ENV['EN_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['EN_CONSUMER_SECRET'] %>
  sandbox: true

development:
  <<: *default

production:
  <<: *default
  sandbox: false
